version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file: .env
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/usr/src/app/
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - 3000:3000

  postgres:
    image: postgres:14.1
    container_name: database
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
